### ISSUE TITLE
highlight.js 高亮出错

### ISSUE THREAD

**Issue by hanai** [Showfom/Affinity#13]
https://github.com/Showfom/Affinity/blob/master/src/js/z.app.js#L2
这里应为 `$('pre code').each(function(i, block) {`

**Comment by jixunmoe** [comment]
之前有做过 isso 评论下的延迟渲染代码框，是按照正确的方法渲染，但是在浏览器访问时也会执行 (即错误的渲染方式，直接提交 `pre` 代码块了)。

因此删除遗留代码实现高亮正确选择语言。
