### ISSUE TITLE
页数超过5会出现翻页按钮

### ISSUE THREAD

**Issue by a1262344305** [Showfom/Affinity#14]
在页数超过5后会出现翻页按钮，按钮没有用而且挡住2
![s70528-230631](https://cloud.githubusercontent.com/assets/17262411/26529849/e42b18a0-438d-11e7-89ec-4928725f06ac.jpg)

**Comment by Showfom** [comment]
@a1262344305 或者可以考虑把 < 改成 ... ？ @JixunMoe

**Comment by Showfom** [comment]
这个按钮的功能是点了以后把前面的页面加载出来 @JixunMoe 麻烦看一下是不是有点 bug

**Comment by jixunmoe** [comment]
可以把 `<>` 换成 `◀▶`，或者类似的 `«»`？

![image](https://cloud.githubusercontent.com/assets/5713045/26632726/f44c83b8-4608-11e7-97c9-6a7f4846ad81.png)

![image](https://cloud.githubusercontent.com/assets/5713045/26632670/c3438e4c-4608-11e7-90a3-e8353afea93f.png)

**Comment by Showfom** [comment]
@JixunMoe 考虑用 emoji 吗？
👈 👉

**Comment by jixunmoe** [comment]
@Showfom 可以改，改的话效果如下：

![image](https://cloud.githubusercontent.com/assets/5713045/26632831/529a84ba-4609-11e7-8546-b2d6a9335699.png)

**Comment by Showfom** [comment]
@JixunMoe 来挑选一个
→ ⇒ ⟹ ⇨ ⇰ ➩ ➪ ➫ ➬ ➭ ➮ ➯ ➲ ➳ ➵ ➸ ➻ ➺ ➼ ➽ ☜ ☟ ➹ ➷ ↶ ↷ ✆ ⌘ ⎋ ⏎ ⏏ ⎈ ⎌ ⍟ ❥ ツ ღ ☻

**Comment by picturepan2** [comment]
感觉第一个最正经吧。

**Comment by a1262344305** [comment]
@Showfom 我一开始还以为是翻页按钮，没想到是加载页码的。。
加载页码我觉得省略号比较不容易误会。。
