### ISSUE TITLE
请问怎么换代码高亮的主题呢？

### ISSUE THREAD

**Issue by abbycin** [Showfom/Affinity#16]
对比下
旧的atom-one-light主题
![2](https://cloud.githubusercontent.com/assets/6814167/26762636/441eaf7a-4978-11e7-9272-b67f6a0dadd7.png)
Affinity自带
![1](https://cloud.githubusercontent.com/assets/6814167/26762643/54ffcc84-4978-11e7-8827-319229481063.png)

果然还是觉得atom-one-light好看些。所以，请问怎么换代码高亮的主题呢？谢谢！

**Comment by picturepan2** [comment]
@abbycin 这个可以直接在 `screen.less` 中搜索 `Dracula Theme v1.2.0` 替换掉带 `.hljs` 开头的样式系列。我们争取会在之后版本分离这部分代码，更方便替换。

**Comment by abbycin** [comment]
哦哦，谢谢！
