### ISSUE TITLE
文章内页图片宽度过大会撑破页面

### ISSUE THREAD

**Issue by Showfom** [Showfom/Affinity#3]
提交修复中

**Comment by jixunmoe** [comment]
若 `code` 太长也会溢出。

**Comment by picturepan2** [comment]
@JixunMoe `code` 太长是有滚动条的，你看到溢出是指 inline 的 `code`？

**Comment by jixunmoe** [comment]
嗯，没有空格的 inline code 会溢出来。

![](https://ooo.0o0.ooo/2017/05/13/5916c8fdd2f3c.png)

**Comment by jixunmoe** [comment]
如果有空格的话倒是会好好的换行。

**Comment by Showfom** [comment]
Fixed
