### ISSUE TITLE
提议：不包括编译后的 min 文件到 repo

### ISSUE THREAD

**Issue by jixunmoe** [Showfom/Affinity#9]
避免 merge 时发生冲突，可以设定一个自动构建服务器进行编译？

**Comment by picturepan2** [comment]
@JixunMoe 看到了 #11 里有调整，觉得用什么 CI 比较好呢？

**Comment by jixunmoe** [comment]
不知道... 没用过 CI 不懂

但是看别的项目好像都是在用 travis ci ?
